name: API CI/CD

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push repo
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Upgrade Pip
        run: python -m pip install --upgrade pip
      - name: Install all dependecies
        run: pip install -r requirements.txt
      - name: Start the API
        run: python API/main.py &
      - name: Run pytest with coverage
        run: python -m pytest
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Fail if coverage is too low
        run: |
          coverage report --fail-under=80        


